import type { Metadata } from "next";
import "./globals.scss";
import LandingHead from "./_components/Head/LandingHead";
import {Inter} from 'next/font/google';
import LandingFooter from "./_components/Footer/LandingFooter";

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <LandingHead />
        {children}
        <LandingFooter />
      </body>
    </html>
  );
}
